apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-productpage
  namespace: student1-bookinfo-dev
  labels:
    app: bookinfo-dev-productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-productpage
  template:
    metadata:
      labels:
        app: bookinfo-dev-productpage
    spec:
      containers:
      - name: bookinfo-dev-productpage
        image: ghcr.io/kittipot321/bookinfo-productpage:dev
        imagePullPolicy: Always
        env:
        - name: DETAILS_HOSTNAME
          value: https://itkmitl.bookinfo.dev.opsta.net/student1/details/details/
        - name: RATINGS_HOSTNAME
          value: http://itkmitl.bookinfo.dev.opsta.net/student1/ratings/ratings/
        - name: REVIEWS_HOSTNAME
          value: http://itkmitl.bookinfo.dev.opsta.net/student1/reviews/reviews/
      imagePullSecrets:
      - name: registry-bookinfo